config/routes.rb
Rails.application.routes.draw do
  resources :themes do
    get "skip", :on => :collection
  end

  resources :women

  resources :posts

  get "/pages/:action" => "pages#:action"

  root 'pages#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  belongs_to :woman
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  validates :woman_id, :presence => true

  def self.info
    {
      1 => {
        :mission => "レベル1　笑顔の写真",
        :mission_text => "まずは、手始めに女の子の写真を撮ろう。",
        :hint_text => "全力の笑顔をお願いしよう。" 
      },
      2 => {
        :mission => "レベル2　ピース写真",
        :mission_text => "日本人だったらこのポーズ<br />ピース写真をとろう。",
        :hint_text => "ピースと言いながら取ると笑顔になる不思議！！" 
      },
      3 => {
        :mission => "レベル3　ばいばい写真",
        :mission_text => "手を振る女の子はとっても可愛いです。",
        :hint_text => "皇族の方はいつもこのポーズです。（笑）" 
      },
      4 => {
        :mission => "レベル4　ジャンプ写真",
        :mission_text => "ジャンプ写真　揺れてる女の子の写真を撮ろう<br />躍動感があるよ。",
        :hint_text => "ジャンプ！ジャンプ！" 
      },
      5 => {
        :mission => "レベル5　2ショット写真",
        :mission_text => "2ショット写真はできるだけ仲良さそうに！！近づいて取ってね。",
        :hint_text => "2ショットだ～！" 
      }
    }
  end
end

app/models/woman.rb
class Woman < ActiveRecord::Base
  has_many :themes
  accepts_nested_attributes_for :themes

  #validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image)
    end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
  end

  def new
    @theme = Theme.new
    @theme.theme_kbn = params[:theme_kbn] || 1
    params[:theme_kbn] = @theme.theme_kbn
    if @theme.theme_kbn == 1       
      woman = Woman.create
      @theme.woman_id = woman.id
    else
      @theme.woman_id = params[:woman_id]
    end
  end

  def edit
  end

  def create
    @theme = Theme.new(theme_params)
    if @theme.save
      if @theme.theme_kbn >= 5
        redirect_to "/pages/complete" and return
        #redirect_to edit_woman_path(@theme.woman_id)
      end
      theme_kbn = @theme.theme_kbn + 1
      redirect_to new_theme_path(:theme_kbn => theme_kbn, :woman_id => @theme.woman_id)
    else
      render :new
    end
  end

  def skip
    theme_kbn = params[:theme_kbn] || 1
    woman_id = params[:woman_id]
    theme_kbn = theme_kbn.to_i
    if theme_kbn >= 5
      #redirect_to edit_woman_path(woman_id) and return
      redirect_to "/pages/complete" and return
    end
    theme_kbn += 1
    redirect_to new_theme_path(:theme_kbn => theme_kbn, :woman_id => woman_id)
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theme_params
      params.require(:theme).permit(:woman_id, :theme_kbn, :photo)
    end
end

app/controllers/women_controller.rb
class WomenController < ApplicationController
  before_action :set_woman, only: [:show, :edit, :update, :destroy]

  # GET /women
  # GET /women.json
  def index
    @women = Woman.all
  end

  # GET /women/1
  # GET /women/1.json
  def show
  end

  def new
    @woman = Woman.new
    @theme = Theme.new
  end

  # GET /women/1/edit
  def edit
    @theme = @women.themes[0] || Theme.new
  end

  # POST /women
  # POST /women.json
  def create
    @woman = Woman.new(woman_params)

    respond_to do |format|
      if @woman.save
        format.html { redirect_to @woman, notice: 'Woman was successfully created.' }
        format.json { render :show, status: :created, location: @woman }
      else
        format.html { render :new }
        format.json { render json: @woman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /women/1
  # PATCH/PUT /women/1.json
  def update
    respond_to do |format|
      if @woman.update(woman_params)
        format.html { redirect_to @woman, notice: 'Woman was successfully updated.' }
        format.json { render :show, status: :ok, location: @woman }
      else
        format.html { render :edit }
        format.json { render json: @woman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /women/1
  # DELETE /women/1.json
  def destroy
    @woman.destroy
    respond_to do |format|
      format.html { redirect_to women_url, notice: 'Woman was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_woman
      @woman = Woman.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def woman_params
      params.require(:woman).permit(:name, :area, :published,
        :woman_attributes => [:photo]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/women_helper.rb
module WomenHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <!--<title><%#= content_for?(:title) ? yield(:title) : "Yukata" %></title> -->
    <title>ユカタスナップ</title>
    <%= csrf_meta_tags %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="/static/css/common.css" type="text/css" />
    <script src="http://code.jquery.com/jquery-latest.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/js/jquery.masonry.min.js"></script>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/complete.html.erb
<div class="contentHeader">
  <%= link_to "戻る", women_path, :class => "backBtn" %>
  <h1 class="contentTitle">ユカタスナップの取り方</h1>
</div>
<div class="coontentBody">
  <p>浴衣スナップ企画へのご協力ありがとうございました！</p>
  <p>Lineでスナップ写真を送ろう！ステキな写真を女の子は欲しがっているはず！</p>

  <script type="text/javascript" src="//media.line.me/js/line-button.js?v=20140411" ></script>
  <script type="text/javascript">
  new media_line_me.LineButton({"pc":false,"lang":"ja","type":"a","text":"かわいい写真撮れたよ！どうもありがとう。今後一緒にご飯とかどう？","withUrl":true});
  </script>
</div>
<div class="contentFooter">
<%= link_to "戻る", women_path, :class => "btn" %>
</div>

app/views/pages/explain.html.erb
<!--
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="../css/common.css" type="text/css" />
    <script src="http://code.jquery.com/jquery-latest.js" type="text/javascript"></script>
    <title>ユカタスナップ</title>
-->
<div class="contentHeader">
  <%= link_to "戻る", women_path, :class => "backBtn" %>
  <h1 class="contentTitle">ユカタスナップで写真撮影！</h1>
</div>
<div class="coontentBody">
  <p><img src="/static/img/snap/snap_start.jpg" width="100%" alt=""></p>
  <p>ユカタスナップではスナップにお題がだされる！<br>
女の子と協力してお題をクリアしよう！<br>
君はどのレベルまでクリアできるかな！？<br>
ぜひ挑戦してみてほしい！</p>
  <div class="btnBox"><%= link_to "進む", new_theme_path, :class => "btn" %></div>
</div>

app/views/pages/index.html.erb
<link rel="stylesheet" href="/static/css/jquery.bxslider.css" type="text/css" />
<script src="/static/js/jquery.bxslider.js"></script>
		<script>
		$(function() {
			$('.bxslider').bxSlider({
			  infiniteLoop: false,
			  hideControlOnEnd: true,
				// onSlideAfter: function(){
				// 	if($(".bx-default-pager .bx-pager-item:eq(3) a").hasClass('active')) {
				// 		alert('A slide has finished transitioning. Bravo. Click OK to continue!');
				// 	}
  		// 		}
			});
		});
		</script>
		<title>ユカタスナップ</title>
	</head>
	<body>
		<div class="coontentBody" style="margin: 0;">
			<ul class="bxslider">
				<li><img src="/static/img/tr1.jpg" width="100%" alt=""></li>
				<li><img src="/static/img/tr2.jpg" width="100%" alt=""></li>
				<li><img src="/static/img/tr3.jpg" width="100%" alt=""></li>
				<li><img src="/static/img/tr4.jpg" width="100%" alt=""></li>
				<li><img src="/static/img/tr5.jpg" width="100%" alt=""></li>
			</ul>
			<div class="btnBox">
				<%= link_to "利用開始", women_path, :class => "startBtn btn" %>
			</div>
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.file_field :image %>
    <%= image_tag @post.image.url(:thumb) %>
    <br />
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>

<script>
$(document).ready(function() {
  var $container = $('#container');
  // initialize
  $container.masonry({
    columnWidth: 100,
    itemSelector: '.item'
  });
});
</script>

<div id="container">
  <% @posts.each do |post| %>
    <div class="item"><%= link_to edit_post_path(post) do %><%= image_tag post.image.url(:medium) %><% end %></div>
  <% end %>
  <div class="item"><img src="http://livedoor.blogimg.jp/chokonyan/imgs/9/9/99fb3e5a.JPG"></div>
  <div class="item"><img src="http://event.rakuten.co.jp/highclass/selection/img/thumb/luxury01/200906/16/luxury138_01_02.jpg"></div>
  <div class="item w2"><img src="http://image.rakuten.co.jp/so-bien/cabinet/yu/luxjewel/lux13koa-f11-3411.jpg"></div>
  <div class="item"><img src="http://pds.exblog.jp/pds/1/201009/24/08/c0128108_0171757.jpg"></div>
  <div class="item"><img src="http://livedoor.blogimg.jp/chokonyan/imgs/9/9/99fb3e5a.JPG"></div>
  <div class="item"><img src="http://livedoor.blogimg.jp/chokonyan/imgs/9/9/99fb3e5a.JPG"></div>
  <div class="item"><img src="http://livedoor.blogimg.jp/chokonyan/imgs/9/9/99fb3e5a.JPG"></div>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>


<!--
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%=l post.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

-->

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @post.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag @post.image.url(:thumb) %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/themes/_form.html.erb
<!--
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="../css/common.css" type="text/css" />
    <script src="http://code.jquery.com/jquery-latest.js" type="text/javascript"></script>
    <title>ユカタスナップ</title>
-->
<% theme_kbn = params[:theme_kbn].to_i %>
<% info = Theme.info[theme_kbn] %>
<%= form_for(@theme) do |f| %>
<div class="contentHeader">
  <%= link_to "戻る", women_path, :class => "backBtn" %>
  <h1 class="contentTitle">ユカタスナップの取り方</h1>
</div>
<div class="coontentBody">
  <p><img src="/static/img/snap/snap<%= theme_kbn %>.jpg" width="100%" alt=""></p>
  <h2 class="subTitle">ミッション</h2>
  <p class="themeTxt"><%= info[:mission].html_safe %></p>
  <p><%= info[:mission_text].html_safe %></p>
  
  <div class="hintBox">
    <h3 class="hintTitle">ヒント</h3>
    <p><%= info[:hint_text].html_safe %></p>
  </div>
</div>
<div class="contentFooter">
  <!-- <button id="falseInput" class="btnReset"><img src="/static/img/snap/camera.png" height="30" alt=""></button> -->
  <%= f.submit :class => "btn" %>
  <%= link_to "SKIP", skip_themes_path(:theme_kbn => @theme.theme_kbn, :woman_id => @theme.woman_id), :class => "skipBtn" %>
  <%#= f.submit %>
</div>

<!-- <input id="fileInput" type="file" style="display:none;" /> -->
<%#= f.file_field :photo, :class => "fileInput", :style => "display:none;" %>
<%= f.file_field :photo, :class => "fileInput" %>

<!--
<script>
  $('.fileInput').change(function(){
    // 1. 選択されたファイルがない場合は何もせずにreturn
    if (!this.files.length) {
      return;
    }

    var file = this.files[0],            // 2. files配列にファイルが入っています
      $_img = $(this).siblings('img'), // 3. jQueryのsiblingsメソッドで兄弟のimgを取得
      fileReader = new FileReader();   // 4. ファイルを読み込むFileReaderオブジェクト

    // 5. 読み込みが完了した際のイベントハンドラ。imgのsrcにデータをセット
    fileReader.onload = function(event) {
      // 読み込んだデータの処理
      //location.href = "theme2.html";
      $("#new_theme").submit();
    };

    // 6. 画像読み込み
    fileReader.readAsDataURL(file);
  });

  // input type="file"のスタイルは変え難いので別のボタンから発火させる
  $(document).ready( function() {
    $('#falseInput').click(function(){
      $(".fileInput").click();
    });
  });
</script>
-->

<%= f.hidden_field :woman_id %>
<%= f.hidden_field :theme_kbn %>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing theme</h1>

<%= render 'form' %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<h1>Listing themes</h1>

<table>
  <thead>
    <tr>
      <th>Woman</th>
      <th>Theme kbn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @themes.each do |theme| %>
      <tr>
        <td><%= theme.woman_id %></td>
        <td><%= theme.theme_kbn %></td>
        <td><%= link_to 'Show', theme %></td>
        <td><%= link_to 'Edit', edit_theme_path(theme) %></td>
        <td><%= link_to 'Destroy', theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theme', new_theme_path %>

app/views/themes/new.html.erb
<%= render 'form' %>

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Woman:</strong>
  <%= @theme.woman_id %>
</p>

<p>
  <strong>Theme kbn:</strong>
  <%= @theme.theme_kbn %>
</p>

<%= image_tag @theme.photo.url(:thumb) %>
  

<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>

app/views/women/_form.html.erb
<%= form_for(@woman) do |f| %>
  <% if @woman.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@woman.errors.count, "error") %> prohibited this woman from being saved:</h2>

      <ul>
      <% @woman.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @woman.themes.each do |theme| %>
    <%= image_tag theme.photo.url(:thumb) %>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <%#= f.fields_for @theme do |i| %>
    <%#= i.file_field :photo %>
  <%# end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/women/edit.html.erb
<h1>Editing woman</h1>

<%= render 'form' %>

<%= link_to 'Show', @woman %> |
<%= link_to 'Back', women_path %>

app/views/women/index.html.erb
<script>
$(function(){
  $('#container').masonry({ //ここには敷き詰めたい要素を囲うidなど指定します。
    itemSelector : '.item'  //ここに敷き詰めたい要素のclassを指定します。
  });
});
</script>

<div class="contentHeader">
  <h1 class="contentTitle">ユカタスナップ一覧</h1>
</div>
<div class="coontentBody">
  <div id="container">
    <% @women.each do |woman| %>
      <% if woman.themes[0].present? %>
      <div class="item"><%= image_tag woman.themes[0].photo.url(:medium), :style => "width:100%;" %></div>
      <% end %>
    <% end %>
  </div>
</div>
<div class="contentFooter">
  <!-- <a href="snap_start.html" class="btnB">撮影スタート</a> -->
  <%= link_to '撮影スタート', "/pages/explain", :class => "btn btnB" %></td>
</div>


<!--
    <div class="item">1</div>
    <div class="item" style="height:100px;">2</div>
    <div class="item">3</div>
    <div class="item" style="height:100px;">2</div>
    <div class="item">3</div>
    <div class="item" style="height:200px;">2</div>
    -->

app/views/women/new.html.erb
<h1>New woman</h1>

<%= render 'form' %>

<%= link_to 'Back', women_path %>

app/views/women/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @woman.name %>
</p>

<p>
  <strong>Area:</strong>
  <%= @woman.area %>
</p>

<p>
  <strong>Published:</strong>
  <%= @woman.published %>
</p>

<%= link_to 'Edit', edit_woman_path(@woman) %> |
<%= link_to 'Back', women_path %>